workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 30
    working_directory: ShopeeStockWatcher
    environment:
      java: 17

    scripts:
      - name: Build Debug APK
        script: gradle clean assembleDebug

      - name: Build Release APK
        script: gradle clean assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - your-email@example.com
